# Generated by Django 3.2.5 on 2023-01-26 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearLevel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.CharField(blank=True, max_length=25)),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('contactNumber', models.IntegerField()),
                ('emailAddress', models.CharField(max_length=25)),
                ('guardianNumber', models.IntegerField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentCourse', to='Eportfolio.course')),
                ('genderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentGender', to='Eportfolio.gender')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentProfile', to=settings.AUTH_USER_MODEL)),
                ('yearID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentYearLevel', to='Eportfolio.yearlevel')),
            ],
        ),
    ]
