# Generated by Django 3.2.5 on 2023-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0002_course_gender_studentprofile_yearlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardianName',
            field=models.CharField(default='null', max_length=70),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emailAddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
    ]
