# Generated by Django 3.2.5 on 2023-02-24 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0003_auto_20230224_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectCode', models.CharField(max_length=100)),
                ('subjectName', models.CharField(max_length=100)),
                ('facultyName', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('studentProfileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentSubject', to='Eportfolio.studentprofile')),
            ],
        ),
    ]
