# Generated by Django 3.2.5 on 2023-02-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overallscore', models.IntegerField()),
                ('score', models.IntegerField()),
                ('date', models.DateField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('taskSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectTask', to='Eportfolio.subject')),
            ],
        ),
    ]
