# Generated by Django 3.2.5 on 2023-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0007_alter_subject_studentprofileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectCode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
