# Generated by Django 3.2.5 on 2023-03-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0008_alter_subject_subjectcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('subjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectRubicks', to='Eportfolio.subject')),
                ('taskTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takstypeRubicks', to='Eportfolio.tasktype')),
            ],
        ),
    ]
