# Generated by Django 3.2.5 on 2023-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0009_rubrick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrick',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
