# Generated by Django 3.2.5 on 2023-04-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0010_alter_rubrick_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isProf',
            field=models.BooleanField(default=False),
        ),
    ]
