# Generated by Django 4.0 on 2023-05-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0011_user_isprof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='studentProfileID',
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ishide', models.BooleanField(default=False)),
                ('studentProfileID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentSubject', to='Eportfolio.studentprofile')),
                ('subjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentSubjectID', to='Eportfolio.subject')),
            ],
        ),
    ]
