# Generated by Django 4.0 on 2023-05-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0012_remove_subject_studentprofileid_studentsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='subjectID',
            field=models.CharField(max_length=1000),
        ),
    ]
