# Generated by Django 4.0 on 2023-05-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0013_alter_studentsubject_subjectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='subjectID',
            field=models.IntegerField(),
        ),
    ]
