# Generated by Django 4.0 on 2023-05-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0014_alter_studentsubject_subjectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='studentProfileID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentTask', to='Eportfolio.studentprofile'),
        ),
    ]
