# Generated by Django 4.0 on 2023-05-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0015_task_studentprofileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='subjectID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentSubject', to='Eportfolio.subject'),
        ),
    ]
