# Generated by Django 4.0 on 2023-05-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0016_alter_studentsubject_subjectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subjectStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentSubject', to='Eportfolio.studentsubject'),
        ),
    ]
