# Generated by Django 4.0 on 2023-05-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0017_task_subjectstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='facultyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profSubject', to='Eportfolio.user'),
        ),
    ]
