# Generated by Django 4.0 on 2023-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0018_alter_subject_facultyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectCode',
            field=models.CharField(max_length=100),
        ),
    ]
