# Generated by Django 4.0 on 2023-06-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0019_alter_subject_subjectcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cptypeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gptypeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='units',
        ),
        migrations.CreateModel(
            name='GradePeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfAbsences', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('gptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GPType', to='Eportfolio.gptype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentGP', to='Eportfolio.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GPSubject', to='Eportfolio.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('totalScore', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('cptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CPtype', to='Eportfolio.cptype')),
                ('gpObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CPgradepoint', to='Eportfolio.gradeperiods')),
            ],
        ),
    ]
