# Generated by Django 4.0 on 2023-06-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0021_classperformance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeperiods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
