# Generated by Django 4.0 on 2023-06-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0022_gradeperiods_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrick',
            name='subjectID',
        ),
        migrations.AddField(
            model_name='rubrick',
            name='gpObjt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpRubrick', to='Eportfolio.gradeperiods'),
        ),
        migrations.AlterField(
            model_name='rubrick',
            name='taskTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectRubicks', to='Eportfolio.tasktype'),
        ),
    ]
