# Generated by Django 4.0 on 2023-06-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0024_alter_rubrick_tasktypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeperiods',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradeperiods',
            name='numberOfAbsences',
            field=models.IntegerField(default=0),
        ),
    ]
