# Generated by Django 4.0 on 2023-06-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0026_remove_gradeperiods_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeperiods',
            name='project',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='gradeperiods',
            name='projectTotal',
            field=models.IntegerField(null=True),
        ),
    ]
