# Generated by Django 4.0 on 2023-06-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0027_gradeperiods_project_gradeperiods_projecttotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperformance',
            name='score',
        ),
        migrations.RemoveField(
            model_name='gradeperiods',
            name='project',
        ),
        migrations.RemoveField(
            model_name='gradeperiods',
            name='score',
        ),
    ]
