# Generated by Django 4.0 on 2023-06-04 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0028_remove_classperformance_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperformance',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gradeperiods',
            name='image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subjectStudent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_Type',
        ),
        migrations.AddField(
            model_name='task',
            name='cptype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsertaskType', to='Eportfolio.tasktype'),
        ),
        migrations.AddField(
            model_name='task',
            name='gptype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskGPType', to='Eportfolio.gptype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskSubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectTask', to='Eportfolio.subject'),
        ),
    ]
