# Generated by Django 4.0 on 2023-06-04 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0029_remove_classperformance_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cptype',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsertaskType', to='Eportfolio.tasktype'),
        ),
    ]
