# Generated by Django 4.0 on 2023-06-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0031_task_studentsubject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cptype',
            new_name='taskType',
        ),
        migrations.AlterField(
            model_name='classperformance',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
