# Generated by Django 4.0 on 2023-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0033_subjectrubrick'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='isScholar',
            field=models.BooleanField(null=True),
        ),
    ]
