# Generated by Django 4.0 on 2023-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0034_studentprofile_isscholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperformance',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
