# Generated by Django 4.0 on 2023-06-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0035_alter_classperformance_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalGrade', models.IntegerField()),
                ('studentprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentFinal', to='Eportfolio.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SFSubject', to='Eportfolio.subject')),
            ],
        ),
    ]
