# Generated by Django 4.0 on 2023-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eportfolio', '0036_studentfinalgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfinalgrade',
            name='totalGrade',
            field=models.IntegerField(null=True),
        ),
    ]
