# Generated by Django 4.2.2 on 2023-06-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Eportfolio", "0037_alter_studentfinalgrade_totalgrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courseCode", models.CharField(max_length=100)),
                ("courseDescription", models.CharField(max_length=100)),
                (
                    "assignCourse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Eportfolio.course",
                    ),
                ),
                (
                    "assignYear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Eportfolio.yearlevel",
                    ),
                ),
            ],
        ),
    ]
