# Generated by Django 4.2.2 on 2023-06-08 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Eportfolio", "0038_subjectlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Eportfolio.course",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Eportfolio.yearlevel",
            ),
        ),
    ]
